POST /auction HTTP/1.1
Host: localhost:8080
Content-Type: application/json  

{
  "product_name": "Vintage Clock 1950s",
  "category": "Antiques",
  "description": "A beautiful vintage clock from the 1950s.",
  "condition": 1
}

### GEt /auction/{id} HTTP/1.1
GET /auction/eba96f07-40b1-4a78-b483-bbbdc0ed096b HTTP/1.1
Host: localhost:8080