POST /auction HTTP/1.1
Host: localhost:8080
Content-Type: application/json  

{
  "product_name": "Vintage Clock 1950s",
  "category": "Antiques",
  "description": "A beautiful vintage clock from the 1950s.",
  "condition": 1
}

### GEt /auction/{id} HTTP/1.1
GET /auction/930dd895-74ea-4768-af71-e164d2fc9a3e HTTP/1.1
Host: localhost:8080